version: "3.7"
services:
  api_service:
    image: "fraudriskapp:latest"
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db    
  postgres_db:
    image: "postgres:9.6.24-alpine3.15"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres